### ISSUE TITLE
NullpointerExecption 

### ISSUE THREAD

**Issue by TissieVA** [TissieVA/Distributed-Systems#28]
Malformed database.xml

```
2021-05-17 18:55:51.867  INFO 21489 --- [       Thread-1] b.u.f.e.u.sockets.MulticastSocketServer  : {"type":"find"}
2021-05-17 18:55:51.868  INFO 21489 --- [       Thread-1] b.u.f.e.u.sockets.MulticastSocketServer  : Multicast sent
2021-05-17 18:55:51.869  INFO 21489 --- [       Thread-1] b.u.f.e.u.sockets.MulticastSocketServer  : Listening
2021-05-17 18:55:51.904  INFO 21489 --- [       Thread-1] b.u.f.e.u.sockets.MulticastSocketServer  : Received message type: ns
2021-05-17 18:55:51.904  INFO 21489 --- [       Thread-1] b.u.f.e.u.sockets.MulticastSocketServer  : Nameserver message received
2021-05-17 18:55:51.963  INFO 21489 --- [       Thread-1] b.u.f.e.u.sockets.MulticastSocketServer  : send publish request
Exception in thread "Thread-1" java.lang.NullPointerException
        at be.ua.fti.ei.client.ClientMessageHandler.sendAddNodeRestRequest(ClientMessageHandler.java:105)
        at be.ua.fti.ei.client.ClientMessageHandler.parse(ClientMessageHandler.java:47)
        at be.ua.fti.ei.utils.sockets.MulticastSocketServer.startServer(MulticastSocketServer.java:83)
        at be.ua.fti.ei.utils.sockets.StartSocketThread.run(MulticastSocketServer.java:160)
 ```

**Comment by TissieVA** [comment]
Check publish method
